// pages/index.vue
<script setup lang="ts">
const tagStore = useTagStore()

await callOnce(tagStore.fetchAll)

const selectedTag = ref(tagStore.selectedTag)

watch(selectedTag, (newValue) => {
  tagStore.setSelectedTag(newValue)
});

const message = ref('')

const chatStore = useChatStore()

async function sendMessage() {
  await chatStore.sendMessage({role: 'user', content: message.value})
}
</script>
<template>
  <app-popover v-model="selectedTag" :items="tagStore.tags"/>

  <form class="fixed bottom-6 left-0 right-0 w-1/2 mx-auto" @submit.prevent="sendMessage">
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
        <Icon name="material-symbols:attach-file" size="25" class="text-gray-500"/>
      </div>
      <input v-model="message" type="search" id="default-search"
             class="block w-full p-4 ps-10 text-gray-200 rounded-3xl bg-gray-700 focus:outline-none"
             :placeholder="`Ask ${selectedTag?.details?.family} anything...`" required :disabled="chatStore.isLoading"/>
      <button type="submit"
              class="absolute end-2.5 bottom-3 bg-white disabled:bg-gray-500 rounded-full p-2.5 text-center inline-flex items-center"
              :disabled="message === '' || chatStore.isLoading">
        <Icon v-if="!chatStore.isLoading" name="material-symbols:arrow-upward" size="15"></Icon>
        <Icon v-else name="material-symbols:square-rounded" size="15" class="text-gray-300"></Icon>
      </button>
    </div>
  </form>

  <div class="p-4 w-full flex flex-col h-full">
      <div v-for="item in chatStore.chatHistory">{{item.content}}</div>
  </div>

</template>

// pages/index.tsx
import React, {useEffect, useState} from 'react';
import {useSelector, useDispatch} from 'react-redux';
import {RootState, AppDispatch} from '@/lib/store';
import {fetchTagsData, setSelectedTag} from '@/lib/slices/tagsSlice';
import {Tag} from '@/types/tags';
import {FaArrowUp, FaSpinner} from 'react-icons/fa';
import {sendMessage, fetchChat} from '@/lib/slices/chatSlice';

export default function Home() {
    const dispatch: AppDispatch = useDispatch();
    const tagsData: Tag[] = useSelector((state: RootState) => state.tags.data);
    const tagsStatus = useSelector((state: RootState) => state.tags.status);
    const selectedTag = useSelector((state: RootState) => state.tags.selectedTag);
    const [input, setInput] = useState('');
    const chatData = useSelector((state: RootState) => state.chat.data);
    const chatStatus = useSelector((state: RootState) => state.chat.status);

    const handleTagChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
        const selectedTagModel = event.target.value;
        const tagObject = tagsData.find(tag => tag.model === selectedTagModel) || null;
        dispatch(setSelectedTag(tagObject));
    };

    const handleSendMessage = () => {
        dispatch(sendMessage(input));
    };

    useEffect(() => {
        if (tagsStatus === 'idle') {
            dispatch(fetchTagsData());
        }
    }, [tagsStatus, dispatch]);

    useEffect(() => {
        dispatch(fetchChat());
    }, [dispatch]);

    return <>
        <div
            className="text-white w-1/2 mx-auto text-sm p-4 flex flex-col justify-end h-[calc(100vh-100px)]">
            {chatData.map((chat, chat_index) => <div key={chat_index}
                                                     className={`${chat.message.role === 'user' ? 'justify-end' : 'justify-start'} flex my-4`}>
                <div className="rounded-3xl p-6 bg-gray-800 min-w-24 text-center">{chat.message.content}</div>
            </div>)}
        </div>
        <form className="w-1/2 mx-auto rounded-3xl fixed bottom-6 right-0 left-0 bg-gray-800">
            <div className="flex">
                <select value={selectedTag?.model || ''} disabled={tagsData.length === 0 || chatStatus === 'loading'}
                        onChange={handleTagChange}
                        className="py-2.5 px-4 bg-transparent border-none focus:ring-0 text-gray-500">
                    {tagsData.map((tag) =>
                        <option key={tag.model} value={tag.model}>
                            {tag.name}
                        </option>
                    )}
                </select>

                <div className="relative w-full">
                    <input value={input}
                           onChange={(e) => setInput(e.target.value)}
                           type="search" id="location-search"
                           disabled={tagsData.length === 0 || chatStatus === 'loading'}
                           className=" p-4 w-full z-20 bg-transparent text-white text-lg border-none focus:ring-0 disabled:text-gray-600"
                           placeholder={tagsData.length === 0 ? 'No LLM detected' : `Ask ${selectedTag?.details.family} anything...`}
                           required/>
                    <button onClick={handleSendMessage} disabled={chatStatus === 'loading' || input.length === 0}
                            type="button"
                            className="absolute top-0 end-0 h-full p-5 bg-blue-700 rounded-e-3xl disabled:bg-gray-700">
                        {chatStatus === 'loading' ? <FaSpinner className="animate-spin"/> : <FaArrowUp/>}
                        <span className="sr-only">Search</span>
                    </button>
                </div>
            </div>
        </form>
    </>
}
